site_name: 'SML Supporting Info'
site_description: 'Supporting information and documentation for the SML.'

nav:
  - Overview: ../README.md
  - 'Method Info':
    - 'Date Adjustment': method_info/date-adjustment/date_adjustment.md
    - 'Selective Editing': method_info/selective-editing/selective_editing.md
    - 'Method Info Template': method_info/method_user_note_template.md

plugins:
  - techdocs-core
